### ISSUE TITLE
Assertion failed: Intention Description Dir URL is null: Convert all properties to TornadoFX properties

### ISSUE THREAD

**Issue by sergej-koscejev** [edvin/tornadofx-idea-plugin#14]
Got this exception after installing the plugin and opening LoginApp.kt in tornadofx-samples.

```
Assertion failed: Intention Description Dir URL is null: Convert all properties to TornadoFX properties; ConvertAllPropertiesToFX, PluginClassLoader[no.tornado.tornadofx.idea, 1.5.8.1]
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getDirURL(IntentionActionMetaData.java:109)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:155)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.a(IntentionManagerSettings.java:164)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerMetaData(IntentionManagerSettings.java:155)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerIntentionMetaData(IntentionManagerSettings.java:73)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.registerIntentionAndMetaData(IntentionManagerImpl.java:145)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.registerIntentionAndMetaData(IntentionManagerImpl.java:122)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.a(IntentionManagerImpl.java:95)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by edvin** [comment]
I think this has to do with missing plugin meta data somehow, but I haven't been able to figure out what's missing. It doesn't seem to make any problems, right? I'll investigate further.

**Comment by edvin** [comment]
Ah, I figured it out. Working on a fix now.

**Comment by edvin** [comment]
Fixed :)

**Comment by slabo** [comment]
so what fixed this? I keep getting this error at my computer at work.

**Comment by edvin** [comment]
Post the code in the class and your exact stack trace.

**Comment by rgrebski** [comment]
@slabo @edvin see referenced commit: https://github.com/edvin/tornadofx-idea-plugin/commit/a48d700f529079f3d895b00e824bc22ce0d58de3
