### ISSUE TITLE
NoSuchMethodError in plugin

### ISSUE THREAD

**Issue by cliffred** [edvin/tornadofx-idea-plugin#19]
IntelliJ keeps reporting a NoSuchMethodError in the TornadoFX plugin.

Version info:
IntelliJ IDEA: 2016.3.4 (#IU-163.12024.16)
Kotlin plugin: 1.1.0-beta-38-IJ2016.3-1
OS: Windows 7

It seems to be caused by this change: https://github.com/JetBrains/kotlin/commit/68174470c3715d7933ebb92d04ea8d7cae712e47

Stacktrace:
```
org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.resolveToDescriptor(Lorg/jetbrains/kotlin/psi/KtDeclaration;)Lorg/jetbrains/kotlin/descriptors/DeclarationDescriptor;
java.lang.NoSuchMethodError: org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.resolveToDescriptor(Lorg/jetbrains/kotlin/psi/KtDeclaration;)Lorg/jetbrains/kotlin/descriptors/DeclarationDescriptor;
	at no.tornado.tornadofx.idea.intentions.AddTableViewColumns.getMemberDescriptor(AddTableViewColumns.kt:107)
	at no.tornado.tornadofx.idea.intentions.AddTableViewColumns.getReturnType(AddTableViewColumns.kt:97)
	at no.tornado.tornadofx.idea.intentions.AddTableViewColumns.isAvailable(AddTableViewColumns.kt:33)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.isAvailable(PsiElementBaseIntentionAction.java:64)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:59)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:132)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:312)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:311)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:219)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by edvin** [comment]
It looks like you're running against the 1.1 beta version of the Kotlin plugin while it is compiled against the 1.0.x API of the plugin. Can you confirm that it works against 1.0.x? I'm not sure if I can easily support the beta with public releases.

**Comment by cliffred** [comment]
This problem does indeed only occur when using the 1.1 beta version of the Kotlin plugin. I don't have any problems when using version 1.0.6-release-IJ2016.3-1 of the Kotlin plugin. I'll just wait for a new release of this plugin after Kotlin 1.1 is final.

**Comment by edvin** [comment]
Great. I will update the plugin to support 1.1 at once when it's released :) Should we close this issue for now?

**Comment by cliffred** [comment]
Great!
Closed as this is not an issue for the current release version (1.0.6) of the Kotlin plugin.
