### ISSUE TITLE
Assertion failed: Intention Description Dir URL is null

### ISSUE THREAD

**Issue by fboldog** [edvin/tornadofx-idea-plugin#2]
Env:
Gradle Kotlin project in IDEA CE 2016.2 Preview
OS X 10.11.5

```
Assertion failed: Intention Description Dir URL is null: Convert to TornadoFX Property; FXPropertyConverter, PluginClassLoader[no.tornado.tornadofx.idea, 1.0.5]
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:156)
    at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getDirURL(IntentionActionMetaData.java:109)
    at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:155)
    at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.processMetaData(IntentionManagerSettings.java:166)
    at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerMetaData(IntentionManagerSettings.java:157)
    at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerIntentionMetaData(IntentionManagerSettings.java:75)
    at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.registerIntentionAndMetaData(IntentionManagerImpl.java:139)
    at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.registerIntentionAndMetaData(IntentionManagerImpl.java:116)
    at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.lambda$registerIntentionFromBean$0(IntentionManagerImpl.java:94)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:377)
    at com.intellij.util.Alarm$Request.run(Alarm.java:388)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
    at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by edvin** [comment]
Thanks for reporting this. It seems like I'm missing some meta data for the intentions, should be an easy fix. Does this break the intention for you, or is it working despite the exception?

**Comment by fboldog** [comment]
It seems working well. Just little bit annoying popping up exception, when I start the IDEA. :)

**Comment by edvin** [comment]
Absolutely. I'll get it sorted :)

**Comment by edvin** [comment]
Commited a fix for this now. I'll release a new version of the plugin shortly. Thanks again for reporting this!

**Comment by fboldog** [comment]
👍

**Comment by edvin** [comment]
Hi! I just wanted to let you know that TornadoFX 1.5.2 is nearing completion, and that I'll release a new version of the plugin at the same time :)

**Comment by fboldog** [comment]
Awesome

**Comment by edvin** [comment]
Plugin version 1.5.2 is now available with this fix and several other improvements, including Gradle multi module support :)
