### ISSUE TITLE
exception in plugin after update of the idea kotlin plugin

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx-idea-plugin#20]
```    org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.resolveToDescriptor(Lorg/jetbrains/kotlin/psi/KtDeclaration;)Lorg/jetbrains/kotlin/descriptors/DeclarationDescriptor;
java.lang.NoSuchMethodError: org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.resolveToDescriptor(Lorg/jetbrains/kotlin/psi/KtDeclaration;)Lorg/jetbrains/kotlin/descriptors/DeclarationDescriptor;	
at no.tornado.tornadofx.idea.intentions.AddTableViewColumns.getMemberDescriptor(AddTableViewColumns.kt:107)
	at no.tornado.tornadofx.idea.intentions.AddTableViewColumns.getReturnType(AddTableViewColumns.kt:97)
	at no.tornado.tornadofx.idea.intentions.AddTableViewColumns.isAvailable(AddTableViewColumns.kt:33)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.isAvailable(PsiElementBaseIntentionAction.java:64)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:59)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:132)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:312)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:311)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:219)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
    
```

**Comment by edvin** [comment]
There seems to be API differences (as expected) between 1.0 and 1.1. I will release a new version of the plugin soon with support for Kotlin 1.1. This of course will break the plugin for people still on Kotlin 1.0 :(

**Comment by ronsmits** [comment]
is it possible to have 2 plugins? a 1.0 and a 1.1?

**Comment by edvin** [comment]
I don't think a plugin can target a specific Kotlin version, so we should probably just rip the bandaid off and upgrade. If somebody then gets an error, the solution is simply to update IDEA.

**Comment by edvin** [comment]
I have released a new version of the plugin now that is kompatible with Kotlin 1.1.
