### ISSUE TITLE
IntelliJ IDEA freezes on copying a file

### ISSUE THREAD

**Issue by CrazyCoder** [edvin/tornadofx-idea-plugin#34]
Originally reported here: https://youtrack.jetbrains.com/issue/KT-19448.

Thread dumps indicate that TornadoFX plug-in might be the case:

```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.dispatchPendingEvents(DirectoryIndexImpl.java:98)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:142)
	at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:57)
	at com.intellij.openapi.roots.impl.ModuleFileIndexImpl.isInSourceContent(ModuleFileIndexImpl.java:85)
	at org.jetbrains.kotlin.idea.util.ProjectRootsUtilKt.isInSourceContentWithoutInjected(ProjectRootsUtil.kt:40)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleProductionSourceScope.contains(IdeaModuleInfos.kt:160)
	at org.jetbrains.kotlin.load.java.JavaClassFinderImpl$FilterOutKotlinSourceFilesScope.contains(JavaClassFinderImpl.java:67)
	at com.intellij.psi.NonClasspathClassFinder.a(NonClasspathClassFinder.java:178)
	at com.intellij.psi.NonClasspathClassFinder$$Lambda$1113/1536191273.process(Unknown Source)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:837)
	at com.intellij.psi.NonClasspathClassFinder.a(NonClasspathClassFinder.java:177)
	at com.intellij.psi.NonClasspathClassFinder.findClass(NonClasspathClassFinder.java:101)
	at org.jetbrains.kotlin.idea.core.script.KotlinScriptDependenciesClassFinder.findClass(KotlinScriptDependenciesClassFinder.kt:61)
	at org.jetbrains.kotlin.resolve.jvm.KotlinJavaPsiFacade$KotlinPsiElementFinderWrapperImpl.findClass(KotlinJavaPsiFacade.java:333)
	at org.jetbrains.kotlin.resolve.jvm.KotlinJavaPsiFacade.findClass(KotlinJavaPsiFacade.java:120)
	at org.jetbrains.kotlin.load.java.JavaClassFinderImpl.findClass(JavaClassFinderImpl.java:98)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageScope$classes$1.invoke(LazyJavaPackageScope.kt:73)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageScope$classes$1.invoke(LazyJavaPackageScope.kt:41)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:402)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageScope.findClassifier(LazyJavaPackageScope.kt:134)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageScope.getContributedClassifier(LazyJavaPackageScope.kt:124)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope.getContributedClassifier(JvmPackageScope.kt:51)
	at org.jetbrains.kotlin.resolve.scopes.ChainedMemberScope.getContributedClassifier(ChainedMemberScope.kt:33)
	at org.jetbrains.kotlin.resolve.scopes.AbstractScopeAdapter.getContributedClassifier(AbstractScopeAdapter.kt:44)
	at org.jetbrains.kotlin.resolve.AllUnderImportScope$getContributedClassifier$1.invoke(AllUnderImportScope.kt:68)
	at org.jetbrains.kotlin.resolve.AllUnderImportScope$getContributedClassifier$1.invoke(AllUnderImportScope.kt:28)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:147)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:108)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:131)
	at kotlin.sequences.SequencesKt___SequencesKt.singleOrNull(_Sequences.kt:302)
	at org.jetbrains.kotlin.resolve.AllUnderImportScope.getContributedClassifier(AllUnderImportScope.kt:68)
	at org.jetbrains.kotlin.resolve.lazy.LazyImportScope$getContributedClassifier$1.invoke(LazyImportScope.kt:217)
	at org.jetbrains.kotlin.resolve.lazy.LazyImportScope$getContributedClassifier$1.invoke(LazyImportScope.kt:191)
	at org.jetbrains.kotlin.resolve.lazy.LazyImportResolver$selectSingleFromImports$1.invoke(LazyImportScope.kt:162)
	at org.jetbrains.kotlin.resolve.lazy.LazyImportResolver$selectSingleFromImports$2.invoke(LazyImportScope.kt:168)
	at org.jetbrains.kotlin.resolve.lazy.LazyImportResolver$selectSingleFromImports$2.invoke(LazyImportScope.kt:75)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager.compute(LockBasedStorageManager.java:211)
	at org.jetbrains.kotlin.resolve.lazy.LazyImportResolver.selectSingleFromImports(LazyImportScope.kt:168)
	at org.jetbrains.kotlin.resolve.lazy.LazyImportScope.getContributedClassifier(LazyImportScope.kt:216)
	at org.jetbrains.kotlin.resolve.calls.tower.TowerLevelsKt.getContributedFunctionsAndConstructors(TowerLevels.kt:271)
	at org.jetbrains.kotlin.resolve.calls.tower.TowerLevelsKt.access$getContributedFunctionsAndConstructors(TowerLevels.kt:1)
	at org.jetbrains.kotlin.resolve.calls.tower.ScopeBasedTowerLevel.getFunctions(TowerLevels.kt:188)
	at org.jetbrains.kotlin.resolve.calls.tower.ScopeTowerProcessorsKt$createSimpleFunctionProcessor$1.invoke(ScopeTowerProcessors.kt:194)
	at org.jetbrains.kotlin.resolve.calls.tower.ScopeTowerProcessorsKt$createSimpleFunctionProcessor$1.invoke(ScopeTowerProcessors.kt)
	at org.jetbrains.kotlin.resolve.calls.tower.NoExplicitReceiverScopeTowerProcessor.simpleProcess(ScopeTowerProcessors.kt:111)
	at org.jetbrains.kotlin.resolve.calls.tower.AbstractSimpleScopeTowerProcessor.process(ScopeTowerProcessors.kt:48)
	at org.jetbrains.kotlin.resolve.calls.tower.CompositeScopeTowerProcessor.process(ScopeTowerProcessors.kt:39)
	at org.jetbrains.kotlin.resolve.calls.tower.TowerResolver.processTowerData(TowerResolver.kt:189)
	at org.jetbrains.kotlin.resolve.calls.tower.TowerResolver.access$processTowerData(TowerResolver.kt:71)
	at org.jetbrains.kotlin.resolve.calls.tower.TowerResolver$run$1.invoke(TowerResolver.kt:106)
	at org.jetbrains.kotlin.resolve.calls.tower.TowerResolver.run(TowerResolver.kt:161)
	at org.jetbrains.kotlin.resolve.calls.tower.TowerResolver.runResolve(TowerResolver.kt:76)
	at org.jetbrains.kotlin.resolve.calls.tower.NewResolutionOldInference.runResolution(NewResolutionOldInference.kt:174)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.doResolveCall(CallResolver.java:624)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.doResolveCallOrGetCachedResults(CallResolver.java:534)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.access$100(CallResolver.java:66)
	at org.jetbrains.kotlin.resolve.calls.CallResolver$1.invoke(CallResolver.java:190)
	at org.jetbrains.kotlin.resolve.calls.CallResolver$1.invoke(CallResolver.java:184)
	at org.jetbrains.kotlin.util.PerformanceCounter.time(PerformanceCounter.kt:90)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.computeTasksAndResolveCall(CallResolver.java:184)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.computeTasksAndResolveCall(CallResolver.java:174)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.resolveFunctionCall(CallResolver.java:285)
	at org.jetbrains.kotlin.resolve.calls.CallExpressionResolver.getResolvedCallForFunction(CallExpressionResolver.kt:91)
	at org.jetbrains.kotlin.resolve.calls.CallExpressionResolver.getCallExpressionTypeInfoWithoutFinalTypeCheck(CallExpressionResolver.kt:197)
	at org.jetbrains.kotlin.resolve.calls.CallExpressionResolver.getCallExpressionTypeInfo(CallExpressionResolver.kt:176)
	at org.jetbrains.kotlin.types.expressions.BasicExpressionTypingVisitor.visitCallExpression(BasicExpressionTypingVisitor.java:783)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.visitCallExpression(ExpressionTypingVisitorDispatcher.java:392)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher$ForDeclarations.visitCallExpression(ExpressionTypingVisitorDispatcher.java:55)
	at org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher$1.invoke(ExpressionTypingVisitorDispatcher.java:185)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher$1.invoke(ExpressionTypingVisitorDispatcher.java:172)
	at org.jetbrains.kotlin.util.PerformanceCounter.time(PerformanceCounter.kt:90)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.getTypeInfo(ExpressionTypingVisitorDispatcher.java:172)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.getTypeInfo(ExpressionTypingVisitorDispatcher.java:143)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.getTypeInfo(ExpressionTypingVisitorDispatcher.java:155)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingServices.getBodyExpressionType(ExpressionTypingServices.java:228)
	at org.jetbrains.kotlin.resolve.DescriptorResolver$6.invoke(DescriptorResolver.java:1104)
	at org.jetbrains.kotlin.resolve.DescriptorResolver$6.invoke(DescriptorResolver.java:1100)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
	at org.jetbrains.kotlin.types.DeferredType.getDelegate(DeferredType.java:92)
	at org.jetbrains.kotlin.types.WrappedType.getAnnotations(KotlinType.kt:74)
	at org.jetbrains.kotlin.resolve.lazy.ForceResolveUtil.forceResolveAllContents(ForceResolveUtil.java:105)
	at org.jetbrains.kotlin.resolve.lazy.ForceResolveUtil.doForceResolveAllContents(ForceResolveUtil.java:92)
	at org.jetbrains.kotlin.resolve.lazy.ForceResolveUtil.forceResolveAllContents(ForceResolveUtil.java:41)
	at org.jetbrains.kotlin.resolve.lazy.ForceResolveUtil.forceResolveAllContents(ForceResolveUtil.java:51)
	at org.jetbrains.kotlin.resolve.lazy.ForceResolveUtil.forceResolveAllContents(ForceResolveUtil.java:46)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.doForceResolveAllContents(LazyClassDescriptor.java:591)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.access$300(LazyClassDescriptor.java:75)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor$8.invoke(LazyClassDescriptor.java:250)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor$8.invoke(LazyClassDescriptor.java:247)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.forceResolveAllContents(LazyClassDescriptor.java:579)
	at org.jetbrains.kotlin.resolve.lazy.ForceResolveUtil.doForceResolveAllContents(ForceResolveUtil.java:75)
	at org.jetbrains.kotlin.resolve.lazy.ForceResolveUtil.forceResolveAllContents(ForceResolveUtil.java:41)
	at org.jetbrains.kotlin.idea.caches.resolve.lightClasses.IDELightClassContexts.contextForNonLocalClassOrObject(IDELightClassContexts.kt:101)
	at org.jetbrains.kotlin.idea.caches.resolve.IDELightClassGenerationSupport$createDataHolderForClass$2.invoke(IDELightClassGenerationSupport.kt:75)
	at org.jetbrains.kotlin.idea.caches.resolve.IDELightClassGenerationSupport$createDataHolderForClass$2.invoke(IDELightClassGenerationSupport.kt:60)
	at org.jetbrains.kotlin.idea.caches.resolve.lightClasses.LazyLightClassDataHolder$exactResultLazyValue$1.invoke(LazyLightClassDataHolder.kt:50)
	at org.jetbrains.kotlin.idea.caches.resolve.lightClasses.LazyLightClassDataHolder$exactResultLazyValue$1.invoke(LazyLightClassDataHolder.kt:44)
	at kotlin.SafePublicationLazyImpl.getValue(Lazy.kt:188)
	at org.jetbrains.kotlin.idea.caches.resolve.lightClasses.LazyLightClassDataHolder.getExactResult(LazyLightClassDataHolder.kt)
	at org.jetbrains.kotlin.idea.caches.resolve.lightClasses.LazyLightClassDataHolder.access$getExactResult$p(LazyLightClassDataHolder.kt:44)
	at org.jetbrains.kotlin.idea.caches.resolve.lightClasses.LazyLightClassDataHolder$LazyLightClassData$clsDelegate$2.invoke(LazyLightClassDataHolder.kt:87)
	at org.jetbrains.kotlin.idea.caches.resolve.lightClasses.LazyLightClassDataHolder$LazyLightClassData$clsDelegate$2.invoke(LazyLightClassDataHolder.kt:83)
	at kotlin.SafePublicationLazyImpl.getValue(Lazy.kt:188)
	at org.jetbrains.kotlin.idea.caches.resolve.lightClasses.LazyLightClassDataHolder$LazyLightClassData.getClsDelegate(LazyLightClassDataHolder.kt)
	at org.jetbrains.kotlin.asJava.classes.KtLazyLightClass$clsDelegate$2.invoke(KtLazyLightClass.kt:26)
	at org.jetbrains.kotlin.asJava.classes.KtLazyLightClass$clsDelegate$2.invoke(KtLazyLightClass.kt:23)
	at kotlin.SafePublicationLazyImpl.getValue(Lazy.kt:188)
	at org.jetbrains.kotlin.asJava.classes.KtLazyLightClass.getClsDelegate(KtLazyLightClass.kt)
	at org.jetbrains.kotlin.asJava.classes.KtLazyLightClass.getClsDelegate(KtLazyLightClass.kt:23)
	at org.jetbrains.kotlin.asJava.classes.KtLightClassBase.getDelegate(KtLightClassBase.kt:34)
	at com.intellij.psi.impl.light.AbstractLightClass.getSupers(AbstractLightClass.java:166)
	at no.tornado.tornadofx.idea.FXTools$Companion.isTornadoFXType(FXTools.kt:36)
	at no.tornado.tornadofx.idea.framework.TornadoFXFrameworkDetector.detect(TornadoFXFrameworkDetector.kt:36)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.a(FrameworkDetectionManager.java:228)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.a(FrameworkDetectionManager.java:175)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.access$000(FrameworkDetectionManager.java:59)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager$1.run(FrameworkDetectionManager.java:66)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue$$Lambda$676/1730171018.run(Unknown Source)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2632)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:288)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by CrazyCoder** [comment]
```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:47)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:38)
	at com.intellij.openapi.file.exclude.EnforcedPlainTextFileTypeManager.getInstance(EnforcedPlainTextFileTypeManager.java:118)
	at com.intellij.openapi.file.exclude.EnforcedPlainTextFileTypeFactory.a(EnforcedPlainTextFileTypeFactory.java:97)
	at com.intellij.openapi.file.exclude.EnforcedPlainTextFileTypeFactory.access$000(EnforcedPlainTextFileTypeFactory.java:33)
	at com.intellij.openapi.file.exclude.EnforcedPlainTextFileTypeFactory$1.isMyFileType(EnforcedPlainTextFileTypeFactory.java:48)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.a(FileTypeManagerImpl.java:562)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:534)
	at com.intellij.openapi.vfs.VirtualFile.getFileType(VirtualFile.java:337)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.createFileViewProvider(FileManagerImpl.java:272)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findViewProvider(FileManagerImpl.java:214)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:396)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:180)
	at no.tornado.tornadofx.idea.framework.TornadoFXFrameworkDetector.detect(TornadoFXFrameworkDetector.kt:33)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.a(FrameworkDetectionManager.java:228)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.a(FrameworkDetectionManager.java:175)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.access$000(FrameworkDetectionManager.java:59)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager$1.run(FrameworkDetectionManager.java:66)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue$$Lambda$676/1730171018.run(Unknown Source)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2632)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:288)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) 
```

**Comment by edvin** [comment]
Thank you so much for reporting. I wonder if it's too expensive to run `findFile` on every file in `newFiles` 
 for every call to `detect`. This is what I'm currently doing:

```kotlin
for (file in newFiles) {
    val psiFile: PsiFile? = psiManager.findFile(file)
    if (psiFile is KtFile) {
        for (clazz in psiFile.classes) {
            if (clazz != null && FXTools.isTornadoFXType(clazz))
                return super.detect(mutableListOf(file), context)
        }
    }
}
```

I will see if I can find other examples of how to detect a class within the given files without using so much resources.

**Comment by edvin** [comment]
I think I misunderstood how this works. I've committed a fix now.

**Comment by edvin** [comment]
I've attached a new version of the plugin which hopefully resolves this. Will do some more testing later today and do a new release.

[tornadofx-idea-plugin.zip](https://github.com/edvin/tornadofx-idea-plugin/files/1200535/tornadofx-idea-plugin.zip)

**Comment by donnerpeter** [comment]
Yes, findFile can be quite expensive at times. I'd suggest to check the file type by name first (com.intellij.openapi.fileTypes.FileTypeRegistry#getFileTypeByFileName). isTornadoFXType also performs resolve operations (very expensive in Kotlin), which'd better be avoided on Swing thread. If a more lightweight check is possible, I'd suggest to do it instead of resolving supertypes.

**Comment by edvin** [comment]
Thanks for the feedback. My attempt at a fix included constraining the file types like so:

```kotlin
override fun createSuitableFilePattern(): ElementPattern<FileContent> {
    return FileContentPattern.fileContent().withName(StandardPatterns.string().endsWith(".kt"));
}
```

I also return `context.createDetectedFacetDescriptions()` directly now instead of calling super.

The check is based on finding if a class in the Kotlin files are subtypes of any `tornadofx.` classes. Can you think of any other way to detect if TornadoFX is in use? Perhaps I could just access the objects as a String and look for `tornadofx` somehow instead?

**Comment by edvin** [comment]
Maybe I could check for imports instead for example?

**Comment by donnerpeter** [comment]
Yes, checking for imports could be faster, but might be incorrect if you allow tornadofx to be a non-direct superclass. But this is most likely fine for framework autodetection purposes.

**Comment by edvin** [comment]
Great, thank you! I will try something like this:

```kotlin
fun containsTornadoFXImports(psiClass: PsiClass) = KtImportList(psiClass.node).imports.find {
    it.textMatches("tornadofx")
} != null
```

**Comment by donnerpeter** [comment]
`KtImportList(psiClass.node)`? I doubt this will work, it's class node, not the import list's. You can probably get `KtImportList` from file, and then `KtImportDirective`-s from it. I'd get `getImportedFqName` from those and check it to avoid costly stub-AST switch.

**Comment by edvin** [comment]
Thanks for the pointers, I will give it a shot :)

**Comment by edvin** [comment]
That seems to work just fine, thanks a lot for the help :)

```kotlin
fun containsTornadoFXImports(file: KtFile) = file.importList?.imports?.find {
    it.text.contains("tornadofx")
} != null
```

**Comment by edvin** [comment]
Plugin version 1.7.9 is released with this fix :)

**Comment by donnerpeter** [comment]
`PsiElement.getText` is a potentially expensive method. I'd still recommend to use stub-based `getImportedFqName`

**Comment by edvin** [comment]
Thanks, I did change it to use getImportedFqName before the release, reread your comment after the first commit and fixed it :) I suspect I have made the same mistake in several other places, will fo through the whole code base. Very grateful for your feedback :)

**Comment by SiebelsTim** [comment]
@edvin is this fixed?

**Comment by edvin** [comment]
Yes, let's close :)
