### ISSUE TITLE
Use resolveToDescriptorIfAny() in intentions when possible

### ISSUE THREAD

**Issue by mglukhikh** [edvin/tornadofx-idea-plugin#36]
For example in AddTableViewColumns.kt:115: 

```
val descriptor = declaration?.resolveToDescriptor() // resolveToDescriptorIfAny() is better
```

Otherwise you can have exceptions like below in case when descriptor is not found:

```
org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException: Descriptor wasn't found for declaration FUNCTION_LITERAL
File name: Cis.kt Physical: true Injected: false
@InitiatingFlow
@StartableByRPC
class DeleteIdentity(val id: Identity) : FlowLogic<Unit>() {
    override val progressTracker: ProgressTracker = tracker()

    companion object {
        object LOADING : ProgressTracker.Step("Loading existing identity from vault.")
        object CREATING : ProgressTracker.Step("Building a new transaction to delete identity.")
        object SIGNING : ProgressTracker.Step("Signing transaction.")
        object FINALISING : ProgressTracker.Step("Finalising transaction") {
            override fun childProgressTracker() = FinalityFlow.tracker()
        }

        fun tracker() = ProgressTracker(LOADING, CREATING, SIGNING, FINALISING)
    }

    @Suspendable override fun call(): Unit {
        // Get identity state.
        progressTracker.currentStep = LOADING
        val stateAndRef = serviceHub.vaultQueryService.queryBy<IdentityState> unconsumedStates<IdentityState>().find <caret>{ it.state.data.identity == id }
        // Creating node's public key.
        progressTracker.currentStep = CREATING
        val me = serviceHub.myInfo.legalIdentity
        // Get the notary ref.
        val notary = stateAndRef!!.state.notary
        // All the other nodes on the network.
        val others = serviceHub.networkMapCache.partyNodes.map { it.legalIdentity } - me
        // Create command.
        val command = Command(CisContract.Delete(), me.owningKey)
        // Unsigned transaction with a command and output state.
        val utx = TransactionBuilder(TransactionType.General, notary).withItems(stateAndRef, command)
        // Sign transaction.
        progressTracker.currentStep = SIGNING
        val stx = serviceHub.signInitialTransaction(utx)
        // Broadcast and record.
        progressTracker.currentStep = FINALISING
        subFlow(FinalityFlow(listOf(stx), others.toSet(), FINALISING.childProgressTracker()))
    }
}
---------------------------------------------------
PluginDeclarationProviderFactory
On failure:
-no synthetic files-
On creation:
-no synthetic files-

	at org.jetbrains.kotlin.idea.project.IdeaAbsentDescriptorHandler.diagnoseDescriptorNotFound(IdeaLocalDescriptorResolver.kt:44)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeImpl.resolveToDescriptor(ResolutionFacadeImpl.kt:67)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.resolveToDescriptor(resolutionApi.kt:42)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.resolveToDescriptor$default(resolutionApi.kt:41)
	at no.tornado.tornadofx.idea.intentions.AddTableViewColumns.getMemberDescriptor(AddTableViewColumns.kt:110)
	at no.tornado.tornadofx.idea.intentions.AddTableViewColumns.getReturnType(AddTableViewColumns.kt:100)
	at no.tornado.tornadofx.idea.intentions.AddTableViewColumns.isAvailable(AddTableViewColumns.kt:35)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:137)
```

**Comment by edvin** [comment]
Thank you, I'll update the code. It's hard to create plugins without proper documentation of the plugin ecosystem features :)

**Comment by edvin** [comment]
Fixed.
